// This file is auto-generated by keycloakify (Vue PoC handler). Do not edit it manually.

/* eslint-disable */
// @ts-nocheck

export type ThemeName = "keycloakify-vue-poc";

export const themeNames: ThemeName[] = ["keycloakify-vue-poc"];

export type KcEnvName = never;
export const kcEnvNames: KcEnvName[] = [];
export const kcEnvDefaults: Record<KcEnvName, string> = {};

export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}
